name: Deploy Vite Build

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Build with Vite into `build/` so Action finds it
      - run: npm run build

      # 5️⃣ Deploy using git-publish-subdir-action
      - name: Publish build folder
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build           # branch where you want the build files
          FOLDER: build           # matches vite.config.js outDir
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
