name: Deploy All Files

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Important: allow GITHUB_TOKEN to push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Your build step (optional)
      - name: Install & Build
        run: |
          npm i
          npm run build
      - name: Add .htaccess to build folder
        run: |
          cat << 'EOF' > build/.htaccess
          # Disable directory listing
          Options -Indexes

          # Redirect all to index.html (SPA support)
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^ index.html [L]
          EOF

      # Ensure .git inside build is removed (if exists)
      # - name: Remove nested .git
      #   run: rm -rf build/.git

      # Create commit before pushing branch
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          # Copy everything except node_modules, .git, and .github
          rsync -av --exclude=node_modules --exclude=.git --exclude=.github ./ deploy/
          # Ensure build folder is also included
          rsync -av build/ deploy/build/
          rm -rf deploy/.git

      - name: Deploy source + build folder
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: deploy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy full project with build: ({sha}) {msg}"
          FORCE_PUSH: true
          
